### PR TITLE
add level 1 drag star to x

### PR DESCRIPTION
**Pull request by yishuzhang0302**
Just as the topic indicates. Thanks!

### CODE REVIEW

**Comment by lidavidm** [comment]
Is this what you meant to commit?

**Comment by yishuzhang0302** [comment]
Yes it is. Thanks you!

**Comment by lidavidm** [comment]
I think I wasn't clear with the task, sorry - what we wanted was to change the very first level to have some hint text, like "Drag the star to the (x)!" I mentioned the definition level because the very first definition level has similar text, which is "Make me a star!"

**Comment by lidavidm** [comment]
Closed in favor of #115

**Pull request closed without merging**
